[build]
builder = "nixpacks"
buildCommand = "yarn install && yarn build"

[deploy]
startCommand = "yarn preview"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10 